"""The panel's QR encoder, pinned to an independent reference.

The firmware carries a fixed V1-L alphanumeric QR encoder (ui/qr_v1.h) and
scripts/mock_device.py carries the same algorithm in Python so the console
mirror shows the code the glass shows. A home-grown QR encoder that is subtly
wrong still LOOKS like a QR code, so eyeballing proves nothing; these matrices
were generated by the `segno` reference library (error='l', mask=0, micro and
error-boost off) and the mock's port must reproduce them bit for bit.

The C side was verified against the same reference on the host when it was
written, and the deployed frame was compared module-for-module after the first
flash (2026-08-12). If this test fails after an encoder change, the C port in
ui/qr_v1.h is wrong too until proven otherwise -- they are the same algorithm.
"""

import importlib.util
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]


def _load_mock():
    spec = importlib.util.spec_from_file_location(
        "mock_device", ROOT / "scripts" / "mock_device.py"
    )
    mod = importlib.util.module_from_spec(spec)
    sys.modules["mock_device"] = mod
    spec.loader.exec_module(mod)
    return mod


# Each row of the 21x21 matrix packed as 21 bits -> 6 hex digits, MSB = x0.
# Generated by: segno.make(payload, error='l', micro=False, mask=0,
#                          boost_error=False)
EXPECTED = {
    "HTTP://127.0.0.1": [
        "1fc57f",
        "104141",
        "17545d",
        "17415d",
        "174b5d",
        "104e41",
        "1fd57f",
        "001400",
        "1df5c4",
        "18b67f",
        "127a60",
        "188b00",
        "1256d1",
        "001a71",
        "1fd9fd",
        "1056e6",
        "175558",
        "174aee",
        "17588d",
        "1054e7",
        "1fd5a9",
    ],
    "HTTP://10.27.27.187": [
        "1fc57f",
        "104141",
        "17545d",
        "17415d",
        "17495d",
        "104e41",
        "1fd57f",
        "001600",
        "1df5c4",
        "062a6f",
        "0bca50",
        "0dacb0",
        "1a7d81",
        "001071",
        "1fdfdc",
        "105de4",
        "1751d8",
        "1742ae",
        "17504d",
        "1057e7",
        "1fdda9",
    ],
}


def test_the_mock_encoder_matches_the_reference_library():
    mock = _load_mock()
    for payload, rows in EXPECTED.items():
        got = mock.qr_v1_encode(payload)
        assert got is not None, f"{payload} refused"
        packed = ["%06x" % int("".join(str(v) for v in row), 2) for row in got]
        assert packed == rows, f"{payload}: matrix diverges from segno's"


def test_the_encoder_refuses_what_cannot_fit_or_scan():
    mock = _load_mock()
    # Lowercase is outside QR's alphanumeric set; silently encoding it in byte
    # mode would need V2 and not fit the panel spot. Refuse, never guess.
    assert mock.qr_v1_encode("http://127.0.0.1") is None
    assert mock.qr_v1_encode("") is None
    assert mock.qr_v1_encode("X" * 26) is None
    # Worst-case dotted quad still fits V1-L.
    assert mock.qr_v1_encode("HTTP://255.255.255.255") is not None
