// A fixed Version-1 QR encoder for the panel's console link.
//
// Deliberately not a general QR library: the payload is always "HTTP://" plus
// a dotted-quad IP -- at most 22 characters, all in QR's alphanumeric set --
// which pins every parameter at compile time: version 1 (21x21), ECC level L
// (the only level whose 19 data codewords fit the worst-case address), mask 0
// (any fixed mask is legal; readers never check that the encoder picked the
// prettiest one). What remains is ~150 lines with no allocation and no tables
// beyond the generator polynomial's arithmetic.
//
// Correctness is pinned two ways: scripts/mock_device.py carries the same
// algorithm in Python and tests/test_qr_v1.py compares it against a matrix
// generated by the `segno` reference library, and the on-device frame was
// verified module-for-module against the same reference after deploy
// (2026-08-12). Change one port and you must change both.
#pragma once

#include <stdint.h>
#include <string.h>

namespace qr_v1 {

constexpr int kSize = 21;

namespace detail {

constexpr int kDataCw = 19;  // V1-L
constexpr int kEccCw = 7;

/** QR alphanumeric value of c, or -1. */
inline int alnum(char c) {
  const char* kSet = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ $%*+-./:";
  const char* p = strchr(kSet, c);
  return (p && c) ? static_cast<int>(p - kSet) : -1;
}

/** GF(256) multiply, polynomial 0x11D. */
inline uint8_t gf_mul(uint8_t a, uint8_t b) {
  int r = 0;
  int aa = a;
  for (int i = 0; i < 8; ++i) {
    if (b & (1 << i))
      r ^= aa << i;
  }
  // reduce
  for (int i = 14; i >= 8; --i)
    if (r & (1 << i))
      r ^= 0x11D << (i - 8);
  return static_cast<uint8_t>(r);
}

struct BitSink {
  uint8_t* out;
  int bits = 0;
  void append(uint32_t val, int n) {
    for (int i = n - 1; i >= 0; --i) {
      if ((val >> i) & 1)
        out[bits >> 3] |= 0x80 >> (bits & 7);
      ++bits;
    }
  }
};

}  // namespace detail

/**
 * Encode `text` into a 21x21 module matrix, out[row][col], 1 = dark.
 *
 * False (and an untouched out) if text is empty, too long for V1-L, or has a
 * character outside the alphanumeric set. Lowercase is OUTSIDE the set on
 * purpose -- the caller upper-cases, which is what keeps the URL in the small
 * encoding in the first place.
 */
inline bool encode(const char* text, uint8_t out[kSize][kSize]) {
  using detail::alnum;
  using detail::BitSink;
  using detail::gf_mul;
  using detail::kDataCw;
  using detail::kEccCw;
  const size_t len = text ? strlen(text) : 0;
  if (len == 0 || len > 25)  // 25 = V1-L alphanumeric capacity
    return false;
  for (size_t i = 0; i < len; ++i)
    if (alnum(text[i]) < 0)
      return false;

  // ---- data codewords -------------------------------------------------------
  uint8_t cw[kDataCw + kEccCw];
  memset(cw, 0, sizeof(cw));
  BitSink sink{cw};
  sink.append(0b0010, 4);
  sink.append(static_cast<uint32_t>(len), 9);
  size_t i = 0;
  for (; i + 1 < len; i += 2)
    sink.append(static_cast<uint32_t>(alnum(text[i]) * 45 + alnum(text[i + 1])), 11);
  if (i < len)
    sink.append(static_cast<uint32_t>(alnum(text[i])), 6);
  const int term = kDataCw * 8 - sink.bits;
  sink.append(0, term < 4 ? term : 4);
  if (sink.bits & 7)
    sink.append(0, 8 - (sink.bits & 7));
  for (int p = 0; sink.bits < kDataCw * 8; ++p) sink.append(p % 2 ? 0x11 : 0xEC, 8);

  // ---- Reed-Solomon ECC -----------------------------------------------------
  // Generator polynomial prod_{j=0..6}(x - alpha^j), built on the fly.
  uint8_t gen[kEccCw + 1];
  memset(gen, 0, sizeof(gen));
  gen[0] = 1;
  uint8_t root = 1;
  for (int d = 0; d < kEccCw; ++d) {
    for (int k = d + 1; k > 0; --k)
      gen[k] = static_cast<uint8_t>(gen[k - 1] ^ gf_mul(gen[k], root));
    gen[0] = gf_mul(gen[0], root);
    root = gf_mul(root, 2);
  }
  // gen[] now holds coefficients lowest-degree-first of the monic generator.
  uint8_t rem[kEccCw];
  memset(rem, 0, sizeof(rem));
  for (int b = 0; b < kDataCw; ++b) {
    const uint8_t factor = cw[b] ^ rem[kEccCw - 1];
    for (int k = kEccCw - 1; k > 0; --k)
      rem[k] = static_cast<uint8_t>(rem[k - 1] ^ gf_mul(gen[k], factor));
    rem[0] = gf_mul(gen[0], factor);
  }
  for (int k = 0; k < kEccCw; ++k) cw[kDataCw + k] = rem[kEccCw - 1 - k];

  // ---- module placement -----------------------------------------------------
  uint8_t mod[kSize][kSize];
  uint8_t isf[kSize][kSize];
  memset(mod, 0, sizeof(mod));
  memset(isf, 0, sizeof(isf));
  auto setf = [&](int x, int y, int v) {
    mod[y][x] = static_cast<uint8_t>(v != 0);
    isf[y][x] = 1;
  };

  // finders + separators
  const int kC[3][2] = {{3, 3}, {kSize - 4, 3}, {3, kSize - 4}};
  for (auto& c : kC)
    for (int dy = -4; dy <= 4; ++dy)
      for (int dx = -4; dx <= 4; ++dx) {
        const int x = c[0] + dx;
        const int y = c[1] + dy;
        if (x < 0 || x >= kSize || y < 0 || y >= kSize)
          continue;
        const int adx = dx < 0 ? -dx : dx;
        const int ady = dy < 0 ? -dy : dy;
        const int d = adx > ady ? adx : ady;
        setf(x, y, d != 2 && d != 4);
      }
  // timing
  for (int t = 8; t < kSize - 8; ++t) {
    setf(t, 6, t % 2 == 0);
    setf(6, t, t % 2 == 0);
  }
  // format info: ECC L (=1), mask 0, BCH remainder, standard XOR mask
  const int fdata = (1 << 3) | 0;
  int frem = fdata;
  for (int r = 0; r < 10; ++r) frem = (frem << 1) ^ ((frem >> 9) * 0x537);
  const int fbits = ((fdata << 10) | frem) ^ 0x5412;
  auto fb = [&](int b) { return (fbits >> b) & 1; };
  for (int b = 0; b < 6; ++b) setf(8, b, fb(b));
  setf(8, 7, fb(6));
  setf(8, 8, fb(7));
  setf(7, 8, fb(8));
  for (int b = 9; b < 15; ++b) setf(14 - b, 8, fb(b));
  for (int b = 0; b < 8; ++b) setf(kSize - 1 - b, 8, fb(b));
  for (int b = 8; b < 15; ++b) setf(8, kSize - 15 + b, fb(b));
  setf(8, kSize - 8, 1);  // the dark module

  // codewords, standard zigzag
  int bit = 0;
  const int total = (kDataCw + kEccCw) * 8;
  for (int right = kSize - 1; right >= 1; right -= 2) {
    if (right == 6)
      right = 5;
    for (int vert = 0; vert < kSize; ++vert) {
      for (int j = 0; j < 2; ++j) {
        const int x = right - j;
        const bool upward = ((right + 1) & 2) == 0;
        const int y = upward ? kSize - 1 - vert : vert;
        if (!isf[y][x] && bit < total) {
          mod[y][x] = (cw[bit >> 3] >> (7 - (bit & 7))) & 1;
          ++bit;
        }
      }
    }
  }
  // mask 0 over data modules
  for (int y = 0; y < kSize; ++y)
    for (int x = 0; x < kSize; ++x)
      if (!isf[y][x] && (x + y) % 2 == 0)
        mod[y][x] ^= 1;

  memcpy(out, mod, sizeof(mod));
  return true;
}

}  // namespace qr_v1
