#!/usr/bin/env python3
"""Embed the built console page into the firmware as a gzipped byte array.

PlatformIO pre-script, and a standalone CLI. Reads ``web/dist/console.html``
(committed, produced by ``npm run build``) and writes
``firmware/arduino/src/generated_page.h``.

Why gzip rather than a raw string literal:

* It is 18 KB instead of 52 KB of flash. On a board sitting at ~82% of its app
  partition that is not a rounding error, and it is ~3x less to push through
  the single-threaded HTTP loop on every page load.
* A byte array cannot accidentally terminate a C++ raw string. The previous
  inline page had to be checked for the sequence ``)html"``; that whole class
  of failure is gone.

Why Python and not the node build: the firmware build only ever needs Python
and PlatformIO. ``npm run build`` regenerates the committed HTML when the
TypeScript changes, but a fresh clone can compile and flash without node
installed at all.
"""

from __future__ import annotations

import gzip
import os
import sys

def repo_root() -> str:
    """Repository root, resolved as a CLI script or as a PlatformIO pre-script.

    SCons exec()s pre-scripts without __file__ in their globals, so fall back to
    walking up from the working directory. Same approach as
    gen_device_header.py -- see the longer explanation there.
    """
    try:
        return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    except NameError:
        pass
    here = os.path.abspath(os.getcwd())
    while True:
        if os.path.isdir(os.path.join(here, "web")) and os.path.isdir(
            os.path.join(here, "scripts")
        ):
            return here
        parent = os.path.dirname(here)
        if parent == here:
            raise RuntimeError("cannot locate repo root; run from inside the repository")
        here = parent


ROOT = repo_root()
PAGE = os.path.join(ROOT, "web", "dist", "console.html")
OUT = os.path.join(ROOT, "firmware", "arduino", "src", "generated_page.h")

BYTES_PER_LINE = 16


def render(raw: bytes) -> str:
    """Format ``raw`` as a C++ header defining the gzipped page."""
    # mtime=0 so the same input always produces the same bytes -- otherwise
    # every build would dirty the header and defeat ccache and the CI drift
    # check alike.
    blob = gzip.compress(raw, compresslevel=9, mtime=0)

    lines = []
    for i in range(0, len(blob), BYTES_PER_LINE):
        chunk = blob[i : i + BYTES_PER_LINE]
        lines.append("    " + " ".join(f"0x{b:02x}," for b in chunk))
    body = "\n".join(lines)

    return (
        "// Auto-generated by scripts/gen_web_page.py from web/dist/console.html.\n"
        "// Do not edit: run `npm --prefix web run build` and rebuild.\n"
        "//\n"
        f"// {len(raw)} bytes of HTML -> {len(blob)} bytes gzipped "
        f"({100 * len(blob) // max(len(raw), 1)}%).\n"
        "// Served with Content-Encoding: gzip; every browser since IE6 accepts it,\n"
        "// but note that a bare `curl http://garage-fan.local/` now needs\n"
        "// --compressed to be readable.\n"
        "#pragma once\n\n"
        "#include <stdint.h>\n\n"
        f"static const uint8_t kPageGz[] = {{\n{body}\n}};\n"
    )


def main() -> int:
    if not os.path.exists(PAGE):
        sys.stderr.write(
            f"ERROR: {os.path.relpath(PAGE, ROOT)} is missing.\n"
            "It is a committed build artifact -- run `npm --prefix web ci && "
            "npm --prefix web run build`.\n"
        )
        return 1

    with open(PAGE, "rb") as f:
        raw = f.read()
    header = render(raw)

    # Only rewrite on a real change, so an unchanged page does not force a
    # recompile of every translation unit that includes it.
    if os.path.exists(OUT):
        with open(OUT, "r") as f:
            if f.read() == header:
                return 0

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write(header)
    return 0


# SCons exec()s pre-scripts with __name__ == "SCons.Script"; see the identical
# guard in gen_device_header.py for why this is not a plain __main__ check.
if __name__ in ("__main__", "SCons.Script"):
    code = main()
    if __name__ == "__main__":
        sys.exit(code)
    elif code != 0:
        raise SystemExit(code)
