#!/usr/bin/env python3
"""Generate the firmware's JSON key names from web/src/types.ts.

PlatformIO pre-script, and a standalone CLI. Reads the TypeScript interfaces
(the wire contract's single source of truth) and writes
``firmware/arduino/src/generated_wire.h``:

    #define WK_SPEED "\\"speed\\""   // for snprintf format strings
    #define WN_SPEED "speed"         // for the series writers, bare name

Why macros and not constexpr strings: the writers build ONE format string per
response by adjacent-literal concatenation (``"{" WK_SPEED ":%d,..."``), which
only the preprocessor can join. The payoff is that a field renamed in types.ts
regenerates this header, and every C++ writer still spelling the old macro
FAILS TO COMPILE -- the rename becomes a build error on both sides instead of
a silent "-" in the UI. tests/test_web_contract.py remains the net for fields
added on one side only.

Fields come from every interface the firmware writes: DeviceState, PlugState,
BatteryState, DeviceInfo, Stats, Sensors, History (plus ApiError's `error`).
Names are deduped -- `voc` in Sensors and History is the same wire key.
"""

from __future__ import annotations

import os
import re
import sys

INTERFACES = [
    "DeviceState",
    "PlugState",
    "BatteryState",
    "DeviceInfo",
    "Stats",
    "Sensors",
    "History",
    "ApiError",
]


def repo_root() -> str:
    """Repository root, as a CLI script or a PlatformIO pre-script.

    SCons exec()s pre-scripts without __file__ in their globals, so fall back
    to walking up from the working directory (see gen_device_header.py).
    """
    try:
        return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    except NameError:
        pass
    here = os.path.abspath(os.getcwd())
    while True:
        if os.path.isdir(os.path.join(here, "web")) and os.path.isdir(
            os.path.join(here, "scripts")
        ):
            return here
        parent = os.path.dirname(here)
        if parent == here:
            raise SystemExit("gen_wire_keys: cannot locate the repo root")
        here = parent


def ts_block(text: str, name: str) -> str:
    """One interface or type alias's body, brace/semicolon-terminated.

    Same parsing rules as tests/test_web_contract.py: interfaces end at the
    first column-0 brace; type aliases (the Sensors union) end at the first
    ';' outside every brace.
    """
    m = re.search(rf"export (?:interface {name}\b[^{{]*{{|type {name}\s*=)", text)
    if not m:
        raise SystemExit(f"gen_wire_keys: {name} missing from types.ts")
    if "interface" in m.group(0):
        end = text.find("\n}", m.start())
        if end == -1:
            raise SystemExit(f"gen_wire_keys: unterminated interface {name}")
        return text[m.start() : end]
    depth = 0
    for i in range(m.end(), len(text)):
        c = text[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
        elif c == ";" and depth == 0:
            return text[m.start() : i]
    raise SystemExit(f"gen_wire_keys: unterminated type alias {name}")


def wire_fields(types_ts: str) -> list[str]:
    """Every wire key the listed interfaces declare, deduped, source order."""
    seen: list[str] = []
    for name in INTERFACES:
        block = ts_block(types_ts, name)
        if block.startswith("export type"):
            fields = re.findall(r"(\w+)\??:", block.split("=", 1)[1])
        else:
            fields = re.findall(r"^\s*(\w+)\??:", block, re.MULTILINE)
        for f in fields:
            if f not in seen:
                seen.append(f)
    return seen


def render(fields: list[str]) -> str:
    lines = [
        "// GENERATED by scripts/gen_wire_keys.py from web/src/types.ts -- do not edit.",
        "// WK_*: the quoted JSON key, for snprintf format strings built by adjacent",
        "// literal concatenation. WN_*: the bare name, for the series writers that",
        "// add their own quoting. A field renamed in types.ts regenerates this file",
        "// and breaks every writer still spelling the old macro at compile time.",
        "#pragma once",
        "// clang-format off",
        "// NOLINTBEGIN",
    ]
    for f in fields:
        up = f.upper()
        lines.append(f'#define WK_{up} "\\"{f}\\":"')
        lines.append(f'#define WN_{up} "{f}"')
    lines.append("// NOLINTEND")
    lines.append("// clang-format on")
    return "\n".join(lines) + "\n"


def main() -> None:
    root = repo_root()
    types_path = os.path.join(root, "web", "src", "types.ts")
    out_path = os.path.join(root, "firmware", "arduino", "src", "generated_wire.h")
    with open(types_path, encoding="utf-8") as f:
        content = render(wire_fields(f.read()))
    # Only touch the file when it changed, so the incremental build stays warm.
    try:
        with open(out_path, encoding="utf-8") as f:
            if f.read() == content:
                return
    except FileNotFoundError:
        pass
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"gen_wire_keys: wrote {os.path.relpath(out_path, root)}", file=sys.stderr)


main()
